name: pip_services3_expressions
version: 1.0.1
description: This library is a part of the [Pip.Services](http://pip.services.org) polyglot microservices toolkit. It provides syntax and lexical analyzers and expression calculator optimized for repeated calculations.
homepage: https://github.com/pip-services3-dart/pip-services3-expressions-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.1.1 <2.0.0"

dev_dependencies:
  test: ^1.17.12